config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get "code", to: 'code#show'
  get "leaderboard", to: 'code#leaderboard'
  post "code/submit"
  post "code/skip"
  post "code/save_draft"
  post "code/get_draft"
  devise_for :teams
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/draft.rb
class Draft < ApplicationRecord
  belongs_to :team
  belongs_to :level
end

app/models/level.rb
class Level < ApplicationRecord
  has_many :level_details
end

app/models/level_detail.rb
class LevelDetail < ApplicationRecord
  belongs_to :team
  belongs_to :level
end

app/models/team.rb
class Team < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :level_details
  has_many :drafts

  def score
    LevelDetail.sum(:score).where(team: self)
  end

  def allowed_in_level(level)
    if level == 1
      true
    else
      @level_detail = LevelDetail.find_by(team: self, level: level - 1)
      @level_detail != nil && @level_detail.cleared

    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name_p1, :name_p2, :college_p1, :college_p2,
                                                          :dept_p1, :dept_p2, :year_p1, :year_p2, :contact_p1, :contact_p2])
  end
end

app/controllers/code_controller.rb
class CodeController < ApplicationController
  before_action :authenticate_team!

  def leaderboard
    @scores = LevelDetail.find_by_sql("
                SELECT team_id,
                name_p1,
                name_p2,
                total,
                DENSE_RANK() OVER (
                    ORDER BY total DESC
                ) AS rank FROM (
                    SELECT team_id,
                    SUM(score_awarded) AS total
                    FROM level_details
                    GROUP BY team_id
                ) AS s
                JOIN teams t
                ON t.id = s.team_id;

              ")
  end


  def submit
    level = params[:level]
    data = params[:data]
    @level = Level.find_by_level level
    result = {}
    result[:accepted] = @level.question_answer == data.chomp
    @level_detail = LevelDetail.find_by team: current_team, level: @level
    if result[:accepted]
      @level_detail.end_time = DateTime.now
      @level_detail.skipped = false
      @level_detail.cleared = true
      @level_detail.score_awarded = calculate_score @level, @level_detail
      @level_detail.save
      if level == 5
        result[:proceed_to] = nil
      else
        result[:proceed_to] = code_path(level: level.to_i + 1)
      end

    else
      @level_detail.wrong_attempts += 1
      @level_detail.save
    end

    render json: {result:  result}
  end
  def skip
    level = params[:level]
    @level = Level.find_by_level level
    @level_detail = LevelDetail.find_by team: current_team, level: @level
    @level_detail.end_time = DateTime.now
    @level_detail.skipped = true
    @level_detail.cleared = true
    @level_detail.score_awarded = calculate_score @level, @level_detail
    if @level_detail.save
      render json: { skipped: true }
    else
      render json: { skipped: false }
    end
  end

  def save_draft
    level = params[:level]
    language = params[:language]
    code = params[:code]
    @level = Level.find_by_level level

    draft = Draft.create team: current_team, level: @level, language: language, code: code
    if draft.save
      render json: { success: true }
    else
      render json: { success: false }
    end
  end

  def get_draft
    level = params[:level]
    language = params[:language]
    @level = Level.find_by_level level
    draft = Draft.order(created_at: :desc).find_by(team: current_team, level: @level, language: language)
    p draft
    if draft.nil?
      render json: { draft: nil }
    else
      render json: { draft: draft }
    end
  end

  def show
    if params[:level].nil?
      redirect_to code_path(level: 1) and return
    end
    if params[:level] == "6"
      render "done" and return
    end
    level = params[:level].to_i
    if current_team.allowed_in_level level
      @level = Level.find_by_level level
      if @level == nil
        redirect_to code_path(level: level - 1)
      end
      @level_detail = LevelDetail.where(team: current_team, level: @level).first_or_create
      @level_detail.start_time ||= DateTime.now
      @level_detail.save
    else
      redirect_to code_path(level: level - 1)
    end
  end

  private
  def calculate_score(level, level_detail)
    score = @level.max_score
    score -= @level_detail.wrong_attempts
    time_taken = @level_detail.end_time - @level_detail.start_time
    score *= (0.9) ** (time_taken / (1000 * 60))
    if level_detail.skipped
      score -= @level.max_score
    end
    score
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/code_helper.rb
module CodeHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/code/done.html.erb
<div class="left">
  <div class="container" id="hero-div">

    <%= image_pack_tag "logo.png", id: "hero-logo" %>
  </div>
  <div class="hero">
    <h1>Darth::Coder();</h1>
    <h2>// May The Source Be With You</h2>
  </div>
  <div class="buttons row">
    <div class="col-sm-12">
      <%= link_to "Log out", destroy_team_session_path, method: :delete, class: "link-main" %>

    </div>


  </div>

  <footer>
    Created by Aniket Bhattacharyea
  </footer>
</div>
<div class="right" data-simplebar>
  <div id="links">
  </div>
  <div class="container">
    <p><h1>Congratulations</h1>
      You have done it! You have completed Darth::Coder();<br>
      It was not an easy task, and you have proved yourself worthy of the Force.
    </p>
  </div>

  <div>
    <!-- <div><span id="python"></span></div> -->
  </div>
</div>

app/views/code/leaderboard.html.erb
<h2>Leaderboard</h2>

<table class="table">
  <thead>
  <tr>
    <th scope="col">Rank</th>
    <th scope="col">Team id</th>
    <th scope="col">Participant 1</th>
    <th scope="col">Participant 2</th>
    <th scope="col">Total</th>
  </tr>
  </thead>
  <tbody>
  <% @scores.each do |score| %>
  <tr>
    <th scope="row"><%= score.rank %></th>
    <td><%= score.team_id %></td>
    <td><%= score.name_p1 %></td>
    <td><%= score.name_p2 %></td>
    <td><%= score.total %></td>
  </tr>
  <% end %>
  </tbody>
</table>

app/views/code/show.html.erb
<nav class="navbar  navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="https://ide.judge0.com">
        Darth Coder
      </a>
    </div>
    <ul class="nav navbar-nav navbar-left">
      <li><a id="apiLink" target="_blank" href=""></a></li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <button id="insertTemplateBtn" type="button" class="btn btn-outline-light mr-sm-2" data-toggle="tooltip" data-placement="bottom" title="Insert template">
        <span class="fas fa-file-word" aria-hidden="true"></span>
      </button>
      <select class="form-control mr-sm-2" id="selectLanguageBtn">
        <option value="4" mode="text/x-csrc">C (gcc 7.2.0)</option>
        <option value="5" mode="text/x-csrc">C (gcc 6.4.0)</option>
        <option value="6" mode="text/x-csrc">C (gcc 6.3.0)</option>
        <option value="7" mode="text/x-csrc">C (gcc 5.4.0)</option>
        <option value="8" mode="text/x-csrc">C (gcc 4.9.4)</option>
        <option value="9" mode="text/x-csrc">C (gcc 4.8.5)</option>
        <option value="10" mode="text/x-c++src">C++ (g++ 7.2.0)</option>
        <option value="11" mode="text/x-c++src">C++ (g++ 6.4.0)</option>
        <option value="12" mode="text/x-c++src">C++ (g++ 6.3.0)</option>
        <option value="13" mode="text/x-c++src">C++ (g++ 5.4.0)</option>
        <option value="14" mode="text/x-c++src">C++ (g++ 4.9.4)</option>
        <option value="15" mode="text/x-c++src">C++ (g++ 4.8.5)</option>
        <option value="22" mode="text/x-go">Go (1.9)</option>
        <option value="26" mode="text/x-java">Java (OpenJDK 9 with Eclipse OpenJ9)</option>
        <option value="27" mode="text/x-java">Java (OpenJDK 8)</option>
        <option value="28" mode="text/x-java">Java (OpenJDK 7)</option>
        <option value="29" mode="text/javascript">JavaScript (nodejs 8.5.0)</option>
        <option value="34" mode="text/x-python">Python (3.6.0)</option>

      </select>
      <button class="btn btn-success mr-sm-3" id="runBtn" data-loading-text="Running...">
       Run
      </button>
      <button class="btn btn-success mr-sm-3" id="submitBtn" data-loading-text="Submitting...">
        Submit
      </button>
      <button class="btn btn-primary mr-sm-3" id="saveBtn" data-loading-text="Saving...">
        Save
      </button>
      <button class="btn btn-primary mr-sm-3" id="skipBtn" data-loading-text="Skipping...">
        Skip
      </button>
      <button class="btn btn-outline-light mr-sm-3" id="loadBtn" data-toggle="tooltip" data-placement="bottom" title="Load previously saved draft">
         Load Saved Draft
      </button>

    </form>

  </div>
</nav>

<div id="sourceEditor"></div>

<div class="container-fluid">
  <div class="row labels">
    <div id="questionLabel" class="col-3 col-sm-3 col-md-3 col-lg-3">
      <h4>
        <span class="fas fa-sign-in-alt" aria-hidden="true"></span> Question <small>(<%= @level.max_score %> marks)</small>

      </h4>

    </div>
    <div id="inputLabel" class="col-3 col-sm-3 col-md-3 col-lg-3">
      <h4>
        <span class="fas fa-sign-in-alt" aria-hidden="true"></span> Input <small>optional</small>
        <button class="btn btn-outline-dark my-sm-2" id="downloadInputBtn" data-toggle="tooltip" data-placement="top" title="Download input">
          <span class="fas fa-download" aria-hidden="true"></span>
        </button>
      </h4>
    </div>
    <div id="outputLabel" class="col-6 col-sm-6 col-md-6 col-lg-6">
      <h4>
        <span class="fas fa-sign-out-alt" aria-hidden="true"></span> Output <small id="emptyIndicator">empty</small>
        <button class="btn btn-outline-dark my-sm-2" id="downloadOutputBtn" data-toggle="tooltip" data-placement="top" title="Download output">
          <span class="fas fa-download" aria-hidden="true"></span>
        </button>
        <small class="pull-right" id="statusLine"></small>
      </h4>
    </div>
  </div>

  <div class="row ioEditors">
    <div class="col-3 col-lg-3">
      <p><%= @level.question_body %></p>

    </div>
    <div id="inputEditor" class="col-3 col-sm-3 col-md-3 col-lg-3"></div>
    <div id="outputEditor" class="col-6 col-sm-6 col-md-6 col-lg-6"></div>
  </div>

  <div class="row">
    <div id="footer" class="col-12 col-sm-12 col-md-12 col-lg-12">
      <p>
        Powered by <a href="https://api.judge0.com">Judge0 API</a>,
      </p>
    </div>
  </div>
</div>
<script>var level = "<%= @level.level %>"</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DarthCoder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
  <script>
      MathJax = {
          tex: {
              inlineMath: [['$', '$'], ['\\(', '\\)']]
          },
          svg: {
              fontCache: 'global'
          }
      };
  </script>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="left">
  <div class="container" id="hero-div">

    <%= image_pack_tag "logo.png", id: "hero-logo" %>
  </div>
  <div class="hero">
    <h1>Darth::Coder();</h1>
    <h2>// May The Source Be With You</h2>
  </div>
  <div class="buttons row">
    <div class="col-sm-12">
      <%= link_to "Log in", new_team_session_path, class: "link-main", id: "about" %>
      <%= link_to "Log out", destroy_team_session_path, method: :delete, class: "link-main" %>

    </div>

  </div>
  <div class="buttons row">
    <% if team_signed_in? %>
      <div class="col-sm-12">
        <%= link_to "Start", code_path(level: 1), class: "link-main" %><br>

      </div>


    <% end %>
  </div>
  <% if team_signed_in? %>
    <h4>Participant 1: </h4> <span><%=  current_team.name_p1 %></span><br>
    <h4>Participant 2: </h4> <span><%= current_team.name_p2 %></span>

<% end %>
  <footer>
    Created by Aniket Bhattacharyea
  </footer>
</div>
<div class="right" data-simplebar>
  <h4>Rules</h4>
  <div id="links">
  </div>
  <div class="container">
    <ol>

      <li>Either individual entries or a team of two is allowed.</li>
      <li>You will be provided a workstation. No need to carry Laptops.</li>
      <li>The languages available are C, C++ (03, 11, 14), Java (7, 8, 9), Python (3.6.0, 2.7.9), and Kotlin. The participants are free to choose any language and the choice can be changed anytime.</li>
      <li>There will be 5 levels. Each level will consist of 1 question, the solution of which will be an integer. The participants will have to write a code that finds and prints the answer.</li>
      <li>Once the participants successfully complete a level, they will be given access to the next level.</li>
      <li>Scores shall be based on - the current level, time taken (starting from the start of the level till the correct answer is recorded), and number of wrong attempts.</li>
      <li>The participants are allowed to run the code locally as many times as they want. Once the code is submitted, if the answer is valid, they can proceed to the next level, otherwise it will count as a wrong answer and points shall be deducted. The participants can submit as many times as they want.</li>
      <li>The participants must carry their college ID cards/proofs.</li>
      <li>Conclusions made by the governing body will be absolute & unchangeable.</li>

    </ol>
  </div>

  <div>
  <!-- <div><span id="python"></span></div> -->
</div>
</div>